// @ts-nocheck
import dynamic from "next/dynamic";
import { LoadingSpinner } from "./LoadingSpinner";

export const componentMap: Record<string, any> = {
  HarmonyColors: dynamic(() => import("@/components/projects/HarmonyColors"), { loading: LoadingSpinner, ssr: false }),
  Hobby: dynamic(() => import("@/components/projects/Hobby"), { loading: LoadingSpinner, ssr: false }),
  HospitalDashboard: dynamic(() => import("@/components/projects/HospitalDashboard"), { loading: LoadingSpinner, ssr: false }),
  InfluencerMatchmaker: dynamic(() => import("@/components/projects/InfluencerMatchmaker"), { loading: LoadingSpinner, ssr: false }),
  InstaChatMessage: dynamic(() => import("@/components/projects/InstaChatMessage"), { loading: LoadingSpinner, ssr: false }),
  Instagram: dynamic(() => import("@/components/projects/Instagram"), { loading: LoadingSpinner, ssr: false }),
  InterestHub: dynamic(() => import("@/components/projects/InterestHub"), { loading: LoadingSpinner, ssr: false }),
  LanguageLearningPlatform: dynamic(() => import("@/components/projects/LanguageLearningPlatform"), { loading: LoadingSpinner, ssr: false }),
  LearnHub: dynamic(() => import("@/components/projects/LearnHub"), { loading: LoadingSpinner, ssr: false }),
  Learning: dynamic(() => import("@/components/projects/Learning"), { loading: LoadingSpinner, ssr: false }),
  LearningApp: dynamic(() => import("@/components/projects/LearningApp"), { loading: LoadingSpinner, ssr: false }),
  LearningPortal: dynamic(() => import("@/components/projects/LearningPortal"), { loading: LoadingSpinner, ssr: false }),
  LinguaLearn: dynamic(() => import("@/components/projects/LinguaLearn"), { loading: LoadingSpinner, ssr: false }),
  LinkRepository: dynamic(() => import("@/components/projects/LinkRepository"), { loading: LoadingSpinner, ssr: false }),
  Lms: dynamic(() => import("@/components/projects/Lms"), { loading: LoadingSpinner, ssr: false }),
  LogisticTracker: dynamic(() => import("@/components/projects/LogisticTracker"), { loading: LoadingSpinner, ssr: false }),
  // MasonryPortfolio: dynamic(() => import("@/components/projects/MasonryPortfolio"), { loading: LoadingSpinner, ssr: false }),
  MeetupHub: dynamic(() => import("@/components/projects/MeetupHub"), { loading: LoadingSpinner, ssr: false }),
  MobileNotes: dynamic(() => import("@/components/projects/MobileNotes"), { loading: LoadingSpinner, ssr: false }),

  MoodZest: dynamic(() => import("@/components/projects/MoodZest"), { loading: LoadingSpinner, ssr: false }),
  MotionPhysics: dynamic(() => import("@/components/projects/MotionPhysics"), { loading: LoadingSpinner, ssr: false }),
  MotorInterface: dynamic(() => import("@/components/projects/MotorInterface"), { loading: LoadingSpinner, ssr: false }),
  MysteriousExplorer: dynamic(() => import("@/components/projects/MysteriousExplorer"), { loading: LoadingSpinner, ssr: false }),
  Netflix: dynamic(() => import("@/components/projects/Netflix"), { loading: LoadingSpinner, ssr: false }),
  NetflixClone: dynamic(() => import("@/components/projects/NetflixClone"), { loading: LoadingSpinner, ssr: false }),
  NewsDebunking: dynamic(() => import("@/components/projects/NewsDebunking"), { loading: LoadingSpinner, ssr: false }),
  NewsLetterArchive: dynamic(() => import("@/components/projects/NewsLetterArchive"), { loading: LoadingSpinner, ssr: false }),
  NonoGram: dynamic(() => import("@/components/projects/NonoGram"), { loading: LoadingSpinner, ssr: false }),
  NoteSharingApp: dynamic(() => import("@/components/projects/NoteSharingApp"), { loading: LoadingSpinner, ssr: false }),
  NotificationSystem: dynamic(() => import("@/components/projects/NotificationSystem"), { loading: LoadingSpinner, ssr: false }),
  Numero: dynamic(() => import("@/components/projects/Numero"), { loading: LoadingSpinner, ssr: false }),
  OSLabSImulator: dynamic(() => import("@/components/projects/OSLabSImulator"), { loading: LoadingSpinner, ssr: false }),
  OfficeTracker: dynamic(() => import("@/components/projects/OfficeTracker"), { loading: LoadingSpinner, ssr: false }),
  OpticsLab: dynamic(() => import("@/components/projects/OpticsLab"), { loading: LoadingSpinner, ssr: false }),
  PMS: dynamic(() => import("@/components/projects/PMS"), { loading: LoadingSpinner, ssr: false }),
  // PalindromeGame: dynamic(() => import("@/components/projects/PalindromeGame"), { loading: LoadingSpinner, ssr: false }),
  // PhotoBooth: dynamic(() => import("@/components/projects/PhotoBooth"), { loading: LoadingSpinner, ssr: false }),
  PhotographyBooking: dynamic(() => import("@/components/projects/PhotographyBooking"), { loading: LoadingSpinner, ssr: false }),
  PlanetaryCollision: dynamic(() => import("@/components/projects/PlanetaryCollision"), { loading: LoadingSpinner, ssr: false }),
};
